site_name: VŠB repozitář pro VaV / VSB R&D Repository

theme:
  name: material #mkdocs #readthedocs
  language: cs

markdown_extensions:
  - smarty
  - admonition
  - pymdownx.details
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid-experimental
  #         format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2:
      arguments:
        securityLevel: 'loose'

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

# nav: # v obsahu zobrazí pouze uvedené; pokud neuvedeno, zobrazí vše
#     - Home: index.md
#     - About: about.md

# vícestupňová hierarchie
# nav:
#     - Home: 'index.md'
#     - 'User Guide':
#         - 'Writing your docs': 'writing-your-docs.md'
#         - 'Styling your docs': 'styling-your-docs.md'
#     - About:
#         - 'License': 'license.md'
#         - 'Release Notes': 'release-notes.md'
